apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gateway
spec:
  gatewayClassName: nginx
  listeners:
    # List of ports to be managed by the gateway
    - name: http
      port: 8080
      protocol: HTTP
      hostname: "*.localtest.me"