apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gateway
spec:
  gatewayClassName: nginx
  listeners:
    # The port to be used is 80 and not the external => 8080 which is only used on the host.
    # This port corresponds to the internal port of the ngf's container / pod
    - name: http-80
      port: 80
      protocol: HTTP
      hostname: "*.localtest.me"