service:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31437
      protocol: TCP
      name: http
    - port: 443
      targetPort: 443
      nodePort: 31438
      protocol: TCP
      name: https